DECLARE @USER VARCHAR(20)= 'LESTER'
DECLARE @EMAIL  VARCHAR(30) = CONCAT(@USER,'@',@USER,'.COM')
DECLARE @PASS VARCHAR(MAX)
SET @PASS = CONVERT(VARCHAR(MAX), HASHBYTES('SHA2_256',@USER), 2)
PRINT @USER + ' ' + @PASS + ' ' + @EMAIL
INSERT INTO USUARIO VALUES (@USER, @PASS, @EMAIL, 1)